[Feature] Dynamic state parent group
ChristopheCVB/TouchPortalPluginSDK pull request #48
Opened 2022-05-09 19:01 UTC by Pjiesco

closes #47

2022-05-10 12:21 UTC, ChristopheCVB requested changes

2022-05-10 12:21 UTC, ChristopheCVB commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +    public boolean sendCreateState(String categoryId, String stateId, String description, Object value, boolean allowEmptyValue, boolean forceUpdate, String parentGroup) {
I don't like the params order and I think we could use the categoryId to retrieve its name and don't ask the developer the parentGroup

2022-05-10 13:34 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +    public boolean sendCreateState(String categoryId, String stateId, String description, Object value, boolean allowEmptyValue, boolean forceUpdate, String parentGroup) {
I also did not really like this order but others would result in more work for backwards compatibility. But i will try again.

Using a categoryId will result in the fact that you can't create these groups based on dynamic data. It would require you to already have the category defined.

2022-05-10 13:50 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +    public boolean sendCreateState(String categoryId, String stateId, String description, Object value, boolean allowEmptyValue, boolean forceUpdate, String parentGroup) {
I have changed up the order of the parameters. I hope this is better.

2022-05-11 10:59 UTC, ChristopheCVB requested changes

2022-05-11 11:11 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
The name doesn't always equal the id. The category name is the name provided in the category annotation. The category id a optional field in the annotation and when not provided its null (or a empty string, not sure). So i will need to check for all cases where the developer could provide the field name, category name or category id

2022-05-11 11:27 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
I think i should also try to check if the categoryId equals the category id thats defined in the plugin constants (generated by the annotation processor)

2022-05-11 12:28 UTC, ChristopheCVB commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
> The name doesn't always equal the id. The category name is the name provided in the category annotation. The category id a optional field in the annotation and when not provided its null (or a empty string, not sure). So i will need to check for all cases where the developer could provide the field name, category name or category id

There's the CategoryHelper for that

2022-05-11 12:28 UTC, ChristopheCVB commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
> I think i should also try to check if the categoryId equals the category id thats defined in the plugin constants (generated by the annotation processor)

That is what the dev is supposed to pass as the categoryId

2022-05-11 12:36 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
> That is what the dev is supposed to pass as the categoryId

But in the example in the readme it passes the name of the enum field of the category and not the actual id from the constants

2022-05-11 12:44 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId)) {
ether way, i've added a check for it

2022-05-11 15:32 UTC, ChristopheCVB requested changes

2022-05-11 15:32 UTC, ChristopheCVB commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                    createStateMessage.addProperty(SentMessageHelper.PARENT_GROUP, CategoryHelper.getCategoryName(subClassField, category));
break outer loop when found

2022-05-18 07:47 UTC, ChristopheCVB requested changes

2022-05-18 07:47 UTC, ChristopheCVB commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId) || categoryId.equals(CategoryHelper.getCategory
These conditions are a bit weird and some don't make sense.
`categoryId` is supposed to the short Category ID, we maybe should add a method to `CategoryHelper` to retrieve it via the field.
Something like `CategoryHelper.getShortCategoryId(Field field, Category category)`
And then the condition would be `categoryId.equals(CategoryHelper.getShortCategoryId(subClassField, category))`

2022-05-18 12:43 UTC, Pjiesco commented on Library/src/main/java/com/christophecvb/touchportal/TouchPortalPlugin.java
> +                                if(category.name().equals(categoryId) || category.id().equals(categoryId) || subClassField.getName().equals(categoryId) || categoryId.equals(CategoryHelper.getCategory
Ah, didn't know that. Makes sense now. WIll add it

2022-05-19 09:53 UTC, ChristopheCVB approved these changes

2022-05-19 09:54 UTC, merged