[API 7] Setting Tooltip
ChristopheCVB/TouchPortalPluginSDK pull request #65
Opened 2023-10-06 13:32 UTC by Pjiesco

Closes #56

2023-10-06 14:55 UTC, ChristopheCVB requested changes

2023-10-06 14:55 UTC, ChristopheCVB commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +            tooltip.addProperty(SettingHelper.Tooltip.TITLE, setting.tooltip().title());
Check if title is not empty before adding it?

2023-10-06 14:55 UTC, ChristopheCVB commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +            tooltip.addProperty(SettingHelper.Tooltip.DOC_URL, setting.tooltip().docUrl());
Check if docUrl is not empty before adding it?

2023-10-06 14:55 UTC, ChristopheCVB commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +
Remove those empty lines

2023-10-07 09:29 UTC, Pjiesco commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +            tooltip.addProperty(SettingHelper.Tooltip.TITLE, setting.tooltip().title());
Should we do the same here? https://github.com/ChristopheCVB/TouchPortalPluginSDK/blob/a527952202346bbedc3d3ecafb1592b34da377cd/AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/utils/SpecUtils.java#L215

2023-10-07 09:31 UTC, Pjiesco commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +            tooltip.addProperty(SettingHelper.Tooltip.DOC_URL, setting.tooltip().docUrl());
Should we do the same here? https://github.com/ChristopheCVB/TouchPortalPluginSDK/blob/a527952202346bbedc3d3ecafb1592b34da377cd/AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/utils/SpecUtils.java#L217

2023-10-08 15:02 UTC, ChristopheCVB commented on AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/SettingProcessor.java
> +            tooltip.addProperty(SettingHelper.Tooltip.TITLE, setting.tooltip().title());
> Should we do the same here?
> 
> https://github.com/ChristopheCVB/TouchPortalPluginSDK/blob/a527952202346bbedc3d3ecafb1592b34da377cd/AnnotationsProcessor/src/main/java/com/christophecvb/touchportal/annotations/processor/utils/SpecUtils.java#L215

Would make sense indeed

2023-10-26 07:29 UTC, ChristopheCVB approved these changes

2023-10-26 07:30 UTC, merged